#!/bin/bash

[ "$(whoami)" != "root" ] && SUDO=sudo

# Detect distro
case $(cat /etc/*-release | grep ^ID= | cut -d= -f2) in
ubuntu) bat=batcat ;;
debian)
  bat=bat
  # Add repositories that are non-free
  $SUDO awk '{print $1" "$2" main contrib non-free non-free-firmware"}' \
    /etc/apt/sources.list >/tmp/sources.list &&
    mv /tmp/sources.list sources.list
  ;;
esac


$SUDO apt install -y curl wget man-db info git

$SUDO apt install -y nala

$SUDO nala install -y \
  atool "$bat" build-essential chafa curl deborphan duf \
  elinks exa exiftool fd-find fzf jq \
  lf lsd man-db mc nala neofetch \
  pkg-config poppler-utils pspg rar ripgrep \
  shellcheck tmux urlview zoxide

if ! command -v lesspipe >/dev/null 2>&1; then
  "$SUDO" apt install exa pkg-config rar -y
  git clone https://github.com/wofr06/lesspipe.git "$HOME/programs/lesspipe"
  (cd "$HOME/programs/lesspipe" && "$SUDO" ./configure && "$SUDO" make install PREFIX=/usr/local)
fi
