#!/bin/bash

[ "$(whoami)" != "root" ] && SUDO=sudo

$SUDO apt install build-essential -y

if ! command -v cargo >/dev/null 2>&1; then
  sh <(curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs) --quiet -y
  source $HOME/.cargo/env
fi

if command -v rustup >/dev/null 2>&1; then
  info Updating rust
  rustup update
fi

cargo install cargo-update lsd du-dust procs ouch zoxide
