#!/bin/bash

#####################################################################
# FUNCTIONS
#
info() {
  tput setaf 4; echo -n "$@"; tput sgr0
}

warning() {
  tput setaf 3 bold; echo -n "$@"; tput sgr0
  sleep 0.5
}

success() {
  tput setaf 2; echo -n "$@"; tput sgr0
}

code() {
  tput dim; echo -n "$@"; tput sgr0
}

instprog() {
  package=$1
  code=$2
  if ! command -v "$package" > /dev/null 2>&1; then
    info "Installing $package...\n"
    eval "$code"
  else
    success "$package is already installed\n"
  fi
}

#####################################################################
# MAIN

info "Updating apt...\n"
sudo apt update \
  && sudo apt upgrade \
  && sudo apt dist-upgrade \
  && sudo apt autoremove \
  && sudo apt autoclean \
  && sudo apt clean

# PACKAGE INSTALLATION TOOLS
# nala (https://gitlab.com/volian/nala)
info "Installing nala"
instprog nala 'sudo apt install nala -y'

info "Installing deborphan\n"
instprog deborphan 'sudo nala install deborphan -y'

info "Installing lanugage pack \n"
sudo apt-get install language-pack-XX

info "Installing curl\n"
instprog curl "sudo nala install curl -y"

# SEARCH TOOLS
# fd (fd-find) is a program to find entries in your filesystem (alternative to find)
# https://github.com/sharkdp/fd
instprog fdfind "sudo nala install fd-find -y"

# rg (ripgrep) ripgrep is a line-oriented search tool that recursively searches 
# the current directory for a regex pattern
# https://github.com/BurntSushi/ripgrep
info "Installing ripgrep\n"
instprog rg "sudo nala install ripgrep -y"

# fzf (Command Line Fuzzy Finder)
# https://github.com/junegunn/fzf
instprog fzf "git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf && ~/.fzf/install"

# Shellcheck - tool for spell checking of bash scripts (a.e. in vim)
# https://github.com/koalaman/shellcheck
instprog shellcheck "sudo nala install shellcheck -y"

# Midnight commander
instprog mc "sudo nala install mc -y"

# batcat https://github.com/sharkdp/bat
instprog batcat 'sudo nala install bat -y'

# pdf-to-text renderer (less will be abele to show .pdf file content)
instprog pdftotext 'sudo nala install poppler-utils -y'

# neofetch - beautiful systen information
instprog neofetch 'sudo nala install neofetch'

# RUST
instprog cc 'sudo nala install build-essential -y'
info "Updating rustup (installing if needed)...\n"
instprog "rustup" "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
rustup update

# hipster things in shell :)
instprog zsh 'sudo nala install zsh -y'

if [[ ! -d "$HOME/.oh-my-zsh" ]]; then
  info "Installing oh-my-zsh...\n"
  sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"/themes/powerlevel10k
else
  success "oh-my-zsh is already installed\n"
fi

zsh_completions=${ZSH_CUSTOM:-${ZSH:-$HOME/.oh-my-zsh}/custom}/plugins/zsh-completions
if [[ ! -d $zsh_completions ]]; then
  info "Installing zsh-completions...\n"
  git clone https://github.com/zsh-users/zsh-completions "$zsh_completions"
else
  success "zsh-completions is already installed\n"
fi

zsh_autosuggestions=${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
if [[ ! -d $zsh_autosuggestions ]]; then
  info "Installing zsh-autosuggestions...\n"
  git clone https://github.com/zsh-users/zsh-autosuggestions "$zsh_autosuggestions"
else
  success "zsh-autosuggestions is already installed\n"
fi

zsh_syntax_highlighting=${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
if [[ ! -d $zsh_syntax_highlighting ]]; then
  info "Installing zsh-syntax-highlighting...\n"
  git clone https://github.com/zsh-users/zsh-syntax-highlighting "$zsh_syntax_highlighting"
else
  success "zsh-syntax-highlighting is already installed\n"
fi

zsh_fzf_tab=${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/fzf-tab
if [[ ! -d $zsh_fzf_tab ]]; then
  info "Installing zsh-fzf-tab...\n"
  git clone https://github.com/Aloxaf/fzf-tab "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}"/plugins/fzf-tab
else
  success "zsh-fzf-tab already installed"
fi

# Lesspipe - less can read archives, directories, pdfs and images
sudo nala install exa
sudo nala install pkg-config rar
git clone https://github.com/wofr06/lesspipe.git "$HOME/programs/lesspipe"
(cd "$HOME/programs/lesspipe" && sudo ./configure && sudo sudo make install PREFIX=/usr/local)
eval lesspipe.sh >> "$HOME/.commonrc"

# chafa - image viewer for terminal
instprog chafa 'sudo nala install chafa'

# lf - light file manager
curl --location --remote-header-name https://github.com/gokcehan/lf/releases/download/r30/lf-linux-amd64.tar.gz \
  | tar --extract --gunzip --directory="$HOME/bin"
git clone https://github.com/gokcehan/lf.git "$HOME/programs/lf"
install -D "$HOME/programs/lf/etc/lf.zsh" "$HOME/.oh-my-zsh/completions/_lf" -m 644
  




info "Installing lsd - color ls" 
instprog lsd 'cargo install lsd'

info "Installing duf - color du"
instprog duf 'sudo nala install duf -y'

mv .zshrc.pre-oh-my-zsh .zshrc


curl --location --remote-name --remote-header-name https://github.com/bootandy/dust/releases/download/v0.8.6/du-dust_0.8.6_amd64.deb
sudo dpkg -i du-dust_0.8.6_amd64.deb
rm du-dust_0.8.6_amd64.deb


# Tmux and features
instprog tmux 'sudo nala install tmux -y'
instprog urlview 'sudo nala install urlview'

git clone https://github.com/gpakosz/.tmux.git "$HOME/programs/.oh-my-tmux"
mkdir -p "$HOME/.config/tmux"
ln -s "$HOME/programs/.oh-my-tmux/.tmux.conf" "$HOME/.config/tmux/tmux.conf"

# Finalizing - clean after all installation
sudo nala autoremove

sudo update-alternatives --config editor
