#!/bin/bash

#####################################################################
# FUNCTIONS
#
info() {
  tput setaf 4; echo -n "$@"; tput sgr0
}

warning() {
  tput setaf 3 bold; echo -n "$@"; tput sgr0
  sleep 0.5
}

success() {
  tput setaf 2; echo -n "$@"; tput sgr0
}

code() {
  tput dim; echo -n "$@"; tput sgr0
}

install() {
  package=$1
  code=$2
  if ! command -v "$package" > /dev/null 2>&1; then
    info "Installing $package...\n"
    eval "$code"
  else
    success "$package is already installed\n"
  fi
}

#####################################################################
# MAIN

info "Updating apt...\n"
sudo apt update \
  && sudo apt upgrade \
  && sudo apt dist-upgrade \
  && sudo apt autoremove \
  && sudo apt autoclean \
  && sudo apt clean

# PACKAGE INSTALLATION TOOLS
# nala (https://gitlab.com/volian/nala)
info "Installing nala"
install nala 'sudo apt install nala -y'

info "Installing deborphan\n"
install deborphan 'sudo nala install deborphan -y'

info "Installing lanugage pack \n"
sudo apt-get install language-pack-XX

info "Installing curl\n"
install curl "sudo nala install curl -y"

# SEARCH TOOLS
# fd (fd-find) is a program to find entries in your filesystem (alternative to find)
# https://github.com/sharkdp/fd
install fdfind "sudo nala install fd-find -y"

# rg (ripgrep) ripgrep is a line-oriented search tool that recursively searches 
# the current directory for a regex pattern
# https://github.com/BurntSushi/ripgrep
info "Installing ripgrep\n"
install rg "sudo nala install ripgrep -y"

# fzf (Command Line Fuzzy Finder)
# https://github.com/junegunn/fzf
install fzf "git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf && ~/.fzf/install"

# Shellcheck - tool for spell checking of bash scripts (a.e. in vim)
# https://github.com/koalaman/shellcheck
install shellcheck "sudo nala install shellcheck -y"

# Midnight commander
install mc "sudo nala install mc -y"

# batcat https://github.com/sharkdp/bat
install batcat 'sudo nala install bat -y'

# pdf-to-text renderer (less will be abele to show .pdf file content)
install pdftotext 'sudo nala install poppler-utils -y'

# RUST
install cc 'sudo nala install build-essential -y'
info "Updating rustup (installing if needed)...\n"
install "rustup" "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
rustup update

# hipster things in shell :)
install zsh 'sudo nala install zsh -y'

if [[ ! -d "$HOME/.oh-my-zsh" ]]; then
  info "Installing oh-my-zsh...\n"
  sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"/themes/powerlevel10k
else
  success "oh-my-zsh is already installed\n"
fi

zsh_completions=${ZSH_CUSTOM:-${ZSH:-$HOME/.oh-my-zsh}/custom}/plugins/zsh-completions
if [[ ! -d $zsh_completions ]]; then
  info "Installing zsh-completions...\n"
  git clone https://github.com/zsh-users/zsh-completions "$zsh_completions"
else
  success "zsh-completions is already installed\n"
fi

zsh_autosuggestions=${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
if [[ ! -d $zsh_autosuggestions ]]; then
  info "Installing zsh-autosuggestions...\n"
  git clone https://github.com/zsh-users/zsh-autosuggestions "$zsh_autosuggestions"
else
  success "zsh-autosuggestions is already installed\n"
fi

zsh_syntax_highlighting=${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
if [[ ! -d $zsh_syntax_highlighting ]]; then
  info "Installing zsh-syntax-highlighting...\n"
  git clone https://github.com/zsh-users/zsh-syntax-highlighting "$zsh_syntax_highlighting"
else
  success "zsh-syntax-highlighting is already installed\n"
fi

zsh_fzf_tab=${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/fzf-tab
if [[ ! -d $zsh_fzf_tab ]]; then
  info "Installing zsh-fzf-tab...\n"
  git clone https://github.com/Aloxaf/fzf-tab "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}"/plugins/fzf-tab
else
  success "zsh-fzf-tab already installed"
fi

zsh_fzf_tab=${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/fzf-zsh-plugin
if [[ ! -d $zsh_fzf_tab ]]; then
  info "Installing fzf-zsh-plugin...\n"
  git clone --depth 1 https://github.com/unixorn/fzf-zsh-plugin.git "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/fzf-zsh-plugin"
else
  success "fzf-zsh-plugin already installed"
fi




info "Installing lsd - color ls" 
install lsd 'sudo nala install lsd -y'

info "Installing duf - color du"
install duf 'sudo nala install duf -y'

mv .zshrc.pre-oh-my-zsh .zshrc

sudo update-alternatives --config editor

# Finalizing - clean after all installation
sudo nala autoremove


#
sudo nala install exa
sudo nala install pkg-config rar
git clone https://github.com/wofr06/lesspipe.git
(cd lesspipe && sudo ./configure && sudo sudo make install PREFIX=/usr/local)
eval lesspipe.sh >> "$HOME/.commonrc"



curl --location --remote-name --remote-header-name https://github.com/bootandy/dust/releases/download/v0.8.6/du-dust_0.8.6_amd64.deb
sudo dpkg -i du-dust_0.8.6_amd64.deb
rm du-dust_0.8.6_amd64.deb
