#!/bin/bash

"$SUDO" apt install zsh git -y

if [[ ! -d "$HOME/.oh-my-zsh" ]]; then
  sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended --keepzshrc
else
  cd "$HOME/.oh-my-zsh" && git pull
fi

zsh_powerlevel10k=${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
if [[ ! -d "$zsh_powerlevel10k" ]]; then
  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "$zsh_powerlevel10k"
else
  cd "$zsh_powerlevel10k" && git pull
fi

zsh_completions=${ZSH_CUSTOM:-${ZSH:-$HOME/.oh-my-zsh}/custom}/plugins/zsh-completions
if [[ ! -d $zsh_completions ]]; then
  git clone https://github.com/zsh-users/zsh-completions "$zsh_completions"
else
  cd "$zsh_completions" && git pull
fi

zsh_autosuggestions=${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
if [[ ! -d $zsh_autosuggestions ]]; then
  git clone https://github.com/zsh-users/zsh-autosuggestions "$zsh_autosuggestions"
else
  cd "$zsh_autosuggestions" && git pull
fi

zsh_syntax_highlighting=${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
if [[ ! -d $zsh_syntax_highlighting ]]; then
  git clone https://github.com/zsh-users/zsh-syntax-highlighting "$zsh_syntax_highlighting"
else
  cd "$zsh_syntax_highlighting" && git pull
fi

zsh_fzf_tab=${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/fzf-tab
if [[ ! -d $zsh_fzf_tab ]]; then
  git clone https://github.com/Aloxaf/fzf-tab "$zsh_fzf_tab"
else
  cd "$zsh_fzf_tab" && git pull
fi

zsh_fzf_history_search=${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-fzf-history-search
if [[ ! -d $zsh_fzf_history_search ]]; then
  git clone https://github.com/joshskidmore/zsh-fzf-history-search \
    "${ZSH_CUSTOM:=$HOME/.oh-my-zsh/custom}/plugins/zsh-fzf-history-search"
else
  cd "$zsh_fzf_history_search" && git pull
fi
