#!/bin/sh
# Common .rc file for both bash and zsh

# Tune manuals
export MANPATH="/usr/local/man:$MANPATH"

[ -d "$HOME/bin" ] && PATH="$HOME/bin:$PATH"
[ -d "$HOME/.local/bin" ] && PATH="$HOME/.local/bin:$PATH"
[ -d "$HOME/.cargo/bin" ] && PATH="$HOME/.cargo/bin:$PATH"
[ -d "$HOME/scripts" ] && PATH="$HOME/scripts:$PATH"

export PATH

export PAGER="less"
export LESSOPEN="| ~/.lessfilter %s"
export LESS='-R -S'
export MANPAGER="sh -c 'col -bx | batcat -l man -p'"
export MANROFFOPT="-c"
export BAT_PAGER="less -RF"
export EDITOR='vim'
export HISTCONTROL=ignoredups
command -v pspg >/dev/null && export PSPG_CONF="$HOME/.config/pspg/.pspgconf"
command -v psql >/dev/null && export PG_PAGER="pspg -X"
command -v psql >/dev/null && export PG_COLORS="error=01;31:warning=01;20:note=01;36:locus=01"
command -v psql >/dev/null && export PG_COLOR="always"
# colored GCC warnings and errors
command -v gcc >/dev/null && export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
# work with GPG encoded content
export GPG_TTY="$TTY"

# Date and Timezone, Lang, Locale etc.
export TZ='Europe/Moscow'
export LANG=ru_RU.UTF-8
export LC_MESSAGES=POSIX

# Pagers: less, bat etc...
# make less more friendly for non-text input files, see lesspipe(1)
if test -x /usr/bin/lesspipe; then
    eval "$(SHELL=/bin/sh lesspipe)"
fi

# shellcheck source=/dev/null
[ -f "${XDG_CACHE_HOME:-$HOME/.config}/aliases" ] && . "${XDG_CACHE_HOME:-$HOME/.config}/aliases"

# shellcheck source=/dev/null
[ -f "${XDG_CACHE_HOME:-$HOME/.config}/fzf/fzf.config.sh" ] && . "${XDG_CACHE_HOME:-$HOME/.config}/fzf/fzf.config.sh"

# pyenv
[ -d "$HOME/.pyenv" ] && export PYENV_ROOT="$HOME/.pyenv"
if [ -e "$PYENV_ROOT/bin" ] ; then
  command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
  eval "$(pyenv init -)"
fi

# nvm
[ -d "$HOME/.nvm" ] && export NVM_DIR="$HOME/.nvm"
# shellcheck source=/dev/null
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# shellcheck source=/dev/null
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

